name: Validate Addon Templates

on:
  push:
    branches:
      - main
    paths:
      - 'templates/**'

jobs:
  validate-addon:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml  # Ensure PyYAML is installed

    - name: Checkout code
      uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Base SHA
      id: base-sha
      run: echo "sha=$(git rev-parse origin/main)" >> $GITHUB_OUTPUT

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v44
      with: 
          base_sha: "${{ steps.base-sha.outputs.sha }}"
      env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
          COUNT: ${{ steps.split-file-names.outputs.word_count }}
      with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            The following files were changed in this pull request:
            ${{ env.ALL_CHANGED_FILES }}

            Total no of changed files: ${{ env.COUNT }}
        