name: Validate Addon Templates

on:
  push:
    branches:
      - main
    paths:
      - 'templates/**'

jobs:
  validate-addon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml  # Ensure PyYAML is installed

    - name: Run validation script
      run: |
        # Outputs a list of changed files
        CHANGED_FILES=$(git diff --name-only origin/main...HEAD)
        # Filter the files that are in the templates folder
        TEMPLATE_FILES=$(echo "$CHANGED_FILES" | grep '^templates/')

        # Pass the filtered list of files to the Python script
        if [ -n "$TEMPLATE_FILES" ]; then
          # Pass the list of changed template files to your script
          python3 validate-template.py $TEMPLATE_FILES
        else
          echo "No template files changed, skipping validation."
        fi