name: Validate Addon Templates

on:
  push:
    branches:
      - main
    paths:
      - 'templates/**'
  pull_request:
    paths:
      - 'templates/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: tj-actions/changed-files@v44
        id: changed-files
        with:
          files: |
            templates/**

      - name: Run validation if templates changed
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
          python3 validate-template.py ${{ steps.changed-files.outputs.all_changed_files }}

        