name: Validate Addon Templates

on:
  push:
    branches:
      - main
    paths:
      - 'templates/**'

jobs:
  validate-addon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml  # Ensure PyYAML is installed

    - name: Run validation script
      run: |
        # Fetch the latest changes from the remote
        git fetch origin

        # Output the list of changed files between the current commit and the base branch
        CHANGED_FILES=$(git diff --name-only origin/$GITHUB_BASE_REF...HEAD)
        echo "Changed files: $CHANGED_FILES"
        