name: Validate Addon Templates

on:
  push:
    branches:
      - main
    paths:
      - 'templates/**'

jobs:
  validate-addon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml  # Ensure PyYAML is installed

    - name: Fetch the latest changes for main (or base branch)
      run: |
          # Fetch the base branch (without overwriting current branch)
          git fetch origin main:refs/remotes/origin/main

      - name: Get changed files
      run: |
          # Use the fetched branch for comparison
          CHANGED_FILES=$(git diff --name-only --diff-filter=d origin/main...HEAD)
          echo "Changed files: $CHANGED_FILES"
        