name: Validate Addon Templates

on:
  push:
    branches:
      - main
    paths:
      - 'templates/**'

jobs:
  validate-addon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml  # Ensure PyYAML is installed

    - name: Modified files
      run: |
          git fetch origin main:main
          git diff --name-only --diff-filter=d main~ main
        